### ISSUE TITLE
New fields in existing modules do not appear in the HubSpot CMS page editor

### ISSUE THREAD

**Issue by umair-khokhar** [HubSpot/cms-js-building-blocks-hello-world#8]
Seems like if you add a new field to an existing `js_module` and deploy, the new field doesn't appear in the HubSpot CMS page editor.
## Steps to reproduce
1. I added a new field to the `hello-world-project/cms-assets/components/modules/TodoList/fields.jsx` under the `FieldGroup` name `default_todo`. 
```
<FieldGroup name="default_todo" label="Default Todo" expanded={false}>
      <TextField
        label="Todo title"
        name="text"
        default="Todo Test 1"
        required
      />
      <TextField
      label="Hello"
      name="hello"
      default="Hello"
        required
      />
      <BooleanField label="Todo Completed" name="completed" default={false} />
</FieldGroup>

```
3. Afterward that  I ran `npm run deploy` command.
4. I went to the CMS page editor and was still not seeing the new field.
<img width="200" alt="Screenshot 2023-01-07 at 12 52 45 PM" src="https://user-images.githubusercontent.com/4765806/211169925-d1e2edb0-4587-464c-a77e-7d677945a6a1.png">

Am I missing anything?

**Comment by timmfin** [comment]
Thanks for the report and apologies for the trouble @umair-khokhar. You are not missing anything, there is a bug here. We thought that we had already fixed this problem, but the issue is still there 😞 

I'll get the team on this!

ps: As a temporary/annoying workaround, I believe you could rename the module folder and re-deploy to force the field changes to show up.

**Comment by umair-khokhar** [comment]
No worries! Thanks so much for getting back to me and proposing a workaround.

**Comment by umair-khokhar** [comment]
I tried renaming the JS module folder, and it didn't work. The module now appears without a label in the page editor.
<img width="1005" alt="Screenshot 2023-01-09 at 9 07 23 AM" src="https://user-images.githubusercontent.com/4765806/211366096-f5edc47a-b67a-4322-bf4f-0c049c9b2474.png">

**Comment by timmfin** [comment]
Hey @umair-khokhar, I wanted to give you can update that we did finally track down and fix this specific bug. However, there is a different but related issue that is cause you to not be able to see/click on JS modules in the editor sidebar now. I'll leave this issue open until we verify that JS modules are working in the page editor (which I hope should be early next week)

**Comment by timmfin** [comment]
@umair-khokhar this is fixed. It actually has been fixed been a few days, and the different issue I mentioned ^ was a distraction (that I've now isolated and dismissed).

Please let us know if you run into any other issues!
